#!/bin/bash
uvicorn main:app --host=0.0.0.0 --port=8080 &
sleep 5
echo "Waiting for the server to start..."
while ! curl -s http://localhost:8080; do
    sleep 1
done
echo "Server is up and running!"
